ruby_version: 2.5

ignore:
  # These are further tuned in .rubocop.yml
  - "**/**":
    - Layout/ExtraSpacing
    - Layout/HashAlignment
    - Style/StringLiterals
    - Style/StringLiteralsInInterpolation
    - Style/TrailingCommaInHashLiteral
