name: Main

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

# Default permissions for all jobs
permissions: {}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read

  test:
    name: Test
    uses: ./.github/workflows/test.yml

  nix:
    name: Nix
    uses: ./.github/workflows/nix.yml
    permissions:
      contents: read
      id-token: write

  complete:
    name: Main (complete)
    needs:
      - test
      - build
      - nix
    runs-on: ubuntu-24.04
    steps:
      - run: echo "DONE!"
