name: Publish
on: workflow_dispatch

concurrency: "publish" # Only one publish job at a time

jobs:
  publish-ruby:
    name: Build and push gem to RubyGems.org
    runs-on: ubuntu-24.04
    environment: "rubygems.org" # see: https://github.com/DataDog/libdatadog-rb/settings/environments
    permissions:
      id-token: write # Required for trusted publishing, see https://github.com/rubygems/release-gem
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - name: Set up Ruby
        uses: ruby/setup-ruby@6ca151fd1bfcfd6fe0c4eb6837eb0584d0134a0c # 1.290.0
        with:
          ruby-version: "4.0"
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - uses: rubygems/release-gem@1c162a739e8b4cb21a676e97b087e8268d8fc40b # v1.1.2
