name: Test
on:
  workflow_call:
  workflow_dispatch:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - os: linux
            cpu: x86_64
            base: ubuntu-24.04 # always x86_64-linux-gnu
          - os: linux
            cpu: aarch64
            base: ubuntu-24.04-arm # always aarch64-linux-gnu
          - os: darwin
            cpu: arm64
            base: macos-15 # always arm64-darwin
        ruby:
          - version: "2.5"
            bundler: "2.3.27"
          - version: "2.6"
            bundler: "2.4.22"
          - version: "2.7"
            bundler: "2.4.22"
          - version: "3.0"
            bundler: "2.5.23"
          - version: "3.1"
            bundler: "2.6.9"
          - version: "3.2"
            bundler: "4.0.3"
          - version: "3.3"
            bundler: "4.0.3"
          - version: "3.4"
            bundler: "4.0.3"
          - version: "4.0"
            bundler: "4.0.3"
        exclude:
          # Ruby 2.5 is not available on arm64-darwin
          - platform:
              os: darwin
            ruby:
              version: "2.5"
    name: Ruby ${{ matrix.ruby.version }} (${{ matrix.platform.cpu }}-${{ matrix.platform.os }})
    runs-on: ${{ matrix.platform.base }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # 7.0.1
      - uses: ruby/setup-ruby@95ef2b042f9d7a56d8268cba8559e2842e2ad01b # 1.321.0
        with:
          ruby-version: ${{ matrix.ruby.version }}
          bundler: ${{ matrix.ruby.bundler }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake
